### ISSUE TITLE
Bar Rank | When user change scale to "Democracy Store"on y axis, Bar along with names shifted to right.

### ISSUE THREAD

**Issue by k6Labz** [Gapminder/vizabi-website#48]
**SEVERITY:** Minor

**MODULE:**  
Bar rank

**Platform:**
-Windows 10/ Chrome

**STEPS TO REPRODUCE:**
1.  Navigate to URL: http://tools-stage.gapminderdev.org/tools/
2.  Tap on Bar rank
3. Change Y-axis scale to "Democracy Scale"

**ACTUAL RESULTS:**
When user change scale to "Democracy Store"on y axis, Bar along with names shifted to right.

**EXPECTED RESULTS:** 
When user change scale to "Democracy Store"on y axis, Bar along with names should not shift to right.

**SCREENSHOT:**
![v14](https://user-images.githubusercontent.com/9950837/28354765-8babf49a-6c7a-11e7-9104-f7db8d4481ad.png)

**Comment by kuguarpwnz** [comment]
@k6Labz this is correct behavior.

**Comment by k6Labz** [comment]
Okay thanks for clarification. Closing issue as per above comment

**Comment by angiehjort** [comment]
wait, what happened with the color scale? @kuguarpwnz @k6Labz

**Comment by kuguarpwnz** [comment]
seems like it's manually changed

**Comment by k6Labz** [comment]
@angieskazka  color was changed manually.
